sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update || true
  - composer update

script:
  - ./vendor/bin/phpunit tests/
