sudo: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  allow_failures:
    - php: 7.2

before_script:
  - composer self-update || true
  - composer validate --strict
  - composer update

script:
  - ./vendor/bin/phpunit tests/
